apiVersion: v1
kind: Secret
metadata:
  name: dockersecret
data:
  .dockerconfigjson: eyJhdXRocyI6IHsibmV4dXMudGJuLmNvLnRoIjogeyJ1c2VybmFtZSI6ICJ0Ym4iLCJwYXNzd29yZCI6ICJWRUpPVFROdVJDRStQQT09IiwiZW1haWwiOiAidGJuLWt0Y0B0Ym4uY28udGgiLCJhdXRoIjogImRHSnVPbFpGU2s5VVZFNTFVa05GSzFCQlBUMD0ifX19
type: kubernetes.io/dockerconfigjson